my:
 greeting : FromServer_Avinash
 list : FromServer_One,FromServer_two,FromServer_three
app:
 name: FromServer_My app
 description : FromServer_Welcome to ${app.name}
dbValues: "{connString:'http://dsfsd/sdfsdf',port:'9090',pass:'password',username:'root'}"
db:
 connection : "https:____/___/"
 port : 9293
 pass : password
 username : root
#Telling actuators to expose every thing 
management.endpoints.web.exposure.include : "*"
 