my:
 greeting : Test Avinash
 list : Test_One,Test_two,Test_three
app:
 name: Test_My app
 description : Test_Welcome to ${app.name}
dbValues: "{connString:'http://dsfsd/sdfsdf',port:'8890',pass:'password',username:'root'}"
db:
 connection : "https:____/___/"
 port : 9293
 pass : password
 username : Test_root
#Telling actuators to expose every thing 
management.endpoints.web.exposure.include : "*"